.TH TRS 1 "17 Jul 1998" "Konwert" "Podrêcznik u¿ytkownika Linuxa"
.SH NAZWA
trs \- filtr zastêpuj±cy ³añcuchy
.SH U¯YCIE
.B trs
.RB [ \- [ r ] e ]
.BI ' ZASTÊPUJ_TO
.I TYM
.RI [ A_TO
.IR TYM ].\|.\|.\|\fB'
.br
.B trs
.RB [ \- [ r ] f ]
.I PLIK
.SH OPIS
Kopiuje stdin na stdout zastêpuj±c ka¿de wyst±pienie danych napisów
innymi. Podobnie jak
.BR tr (1),
ale zamienia napisy, a nie tylko pojedyncze znaki.
.PP
Regu³y (oddzielone odstêpami) mog± byæ podane bezpo¶rednio po opcji
.B \-e
albo mog± byæ przeczytane z
.IR PLIKU .
Argument niepoprzedzony przez
.B \-e
ani
.B \-f
jest interpretowany jako skrypt, je¶li zawiera jakie¶ odstêpy, a jako
nazwa pliku, je¶li nie zawiera.
.PP
Komentarze mo¿na umieszczaæ od
.B #
do koñca linii. Znak
.B #
w napisach musi byæ zapisany jako
.BR \\\\\\\\# .
.PP
Mo¿na u¿ywaæ standardowych eskejpów jak w C:
.B \\\\a \\\\b \\\\e \\\\f \\\\n \\\\r \\\\t \\\\v \\\\\\\\
.BI \\\\\\\\ nnn\fR.
Dodatkowo
.B \\\\s
oznacza spacjê, a
.B \\\\!\|
\- pusty ³añcuch.
.PP
Mo¿na okre¶liæ zbiory dopuszczalnych znaków na danej pozycji pomiêdzy
.B \\\\[
a
.BR \\\\] .
Zakresy ASCII w zbiorach mog± byæ krótko zapisane jako
.IB PIERWSZY \- OSTATNI\fR.
Je¶li zbiór sk³ada siê tylko z pojedynczego zakresu,
.B \\\\[
i
.B \\\\]
mog± byæ pominiête.
.PP
Je¶li czê¶æ napisu do zast±pienia jest ujêta w
.BR \\\\\\\\{ .\|.\|.\| \\\\\\\\} ,
to tylko ta czê¶æ jest zastêpowana. Tekst poza
.BR \\\\\\\\{ .\|.\|.\| \\\\\\\\}
pe³ni rolê warunku: napis jest t³umaczony tylko je¶li jest poprzedzony
danym tekstem i za nim jest inny.
.B \\\\{
na pocz±tku albo
.B \\\\}
na koñcu napisu mog± byæ pominiête. Tekst poza
.BR \\\\\\\\{ .\|.\|.\| \\\\\\\\}
jest traktowany jako nieprzet³umaczony.
.PP
Przed pocz±tkiem pliku i poza jego koñcem s± tylko znaki
.BR \\\\\\\\n .
Na przyk³ad
.B \\\\n\\\\{.\\\\}\\\\n
znajduje
.B .\|
stoj±c± samodzielnie w linii, w³±czaj±c w to pierwsz± liniê, albo
ostatni± nawet bez znacznika
.BR \\\\n .
.PP
Fragment postaci
.BI \\\\\\\\? x = N\fR,
gdzie
.I x
jest liter±
.BR A - Za - z ,
a
.I N
jest cyfr±
.BR 0 - 9 ,
zawarty w napisie docelowym przypisuje zmiennej
.I x
warto¶æ
.IR N ,
kiedy dana regu³a jest u¿yta. Taki fragment w napisie ¼ród³owym
powoduje, ¿e dana regu³a jest brana pod uwagê tylko je¶li ta zmienna ma
tak± warto¶æ. Pocz±tkowo wszystkie zmienne maj± warto¶æ
.BR 0 .
Mo¿e byæ wiele przypisañ lub warunków w jednej regule \- warunki musz±
byæ wtedy wszystkie prawdziwe i wykonywane s± wszystkie przypisania.
.SS OPCJE
.TP
.B \-e
Podaje regu³y konwersji bezpo¶rednio w linii poleceñ.
.TP
.B \-f
Pobiera je z danego pliku.
.TP
.B \-r
Odwraca ka¿d± regu³ê. Dotyczy to tylko nastêpnej opcji
.B -e
albo
.BR -f .
Oczywi¶cie to nie musi daæ odwrotnego t³umaczenia! Ka¿da regu³a
zawieraj±ca które¶ z
.B \\\\{\\\\}\\\\[\\\\]\\\\{\\\\}\\\\\-
jest uwzglêdniana tylko w jednym kierunku. Mo¿na wymusiæ, ¿eby dowolna
regu³a by³a uwzglêdniana tylko w jednym kierunku, umieszczaj±c napis do
przet³umaczenia w
.BR \\\\\\\\{ .\|.\|.\| \\\\\\\\} .
.TP
.B \-\-help
wy¶wietla opis i wychodzi
.TP
.B \-\-version
wy¶wietla informacjê o wersji i wychodzi
.PP
Mo¿e byæ wiele opcji
.B \-e
albo
.BR \-f .
Wszystkie regu³y s± wtedy ³adowane razem, przy czym wcze¶niejsze maj±
pierwszeñstwo.
.SH PRZYK£AD
.nf
$ echo Leeloo |trs -e 'el n e i i aqq o\\}\\n x o u'
Linux
.fi
.SH CZYM SIÊ TO RÓ¯NI OD seda
Podstawowa ró¿nica pomiêdzy
.BR trs em
a
.B sed 's///g;
.RB .\|.\|.\| '
(wy³±czaj±c sedowe wyra¿enia regularne) jest taka, ¿e sed patrzy na
ka¿d± regu³ê w kolejno¶ci ich podania i stosuje j± do ca³ej linii
filtrowanego pliku, podczas gdy trs bada ka¿d± pozycjê i próbuje
wszystkich regu³ na tej pozycji najpierw. W sedzie ka¿da regu³a dostaje
tekst wyprodukowany przez poprzedni±, a w trsie ka¿dy kawa³ek tekstu
jest t³umaczony najwy¿ej raz (je¶li wiêcej ni¿ jedna regu³a pasuje na
danej pozycji, regu³a wymieniona wcze¶niej wygrywa). W³a¶nie dlatego sed
niezbyt nadaje siê do t³umaczenia miêdzy zestawami znaków. Z drugiej
strony, tr t³umaczy tylko pojedyncze bajty, wiêc nie mo¿e byæ u¿yty do
konwersji Unikodu ani TeXowych / SGMLowych sposobów zapisu rozszerzonych
znaków.
.PP
Inny przyk³ad:
.nf
$ echo 642 |trs -e '4 7 72 66 64 4'
42
$ echo 642 |sed 's/4/7/g; s/72/66/g; s/64/4/g'
666
.fi
.PP
Napis do zamiany mo¿e byæ pusty; musi wtedy byæ co¶ poza
.BR \\\\\\\\{\\\\\\\\} .
W tym szczególnym przypadku tylko jedna taka regu³a tworz±ca z niczego
mo¿e byæ zastosowana na danej pozycji. Na przyk³ad
.B \\\\}\\\\x80\\\\\-\\\\xFF @
poprzedza ka¿dy znak z ustawionym najwy¿szym bitem przez
.BR @ .
Regu³a postaci
.B co¶\\\\{ tam
nie dzia³a na koñcu pliku.
.SH "ZOBACZ TE¯"
.BR tr (1),
.BR konwert (1)
.SH COPYRIGHT
Konwert jest pakietem s³u¿±cym do konwersji miêdzy ró¿nymi kodowaniami
znaków.
.PP
Copyright (c) 1998 Marcin 'Qrczak' Kowalczyk
.PP
Niniejszy program jest oprogramowaniem wolnodostêpnym; mo¿esz go
rozprowadzaæ dalej i/lub modyfikowaæ na warunkach Powszechnej Licencji
Publicznej GNU, wydanej przez Fundacjê Wolnodostêpnego Oprogramowania
- wed³ug wersji 2-giej tej Licencji lub której¶ z pó¼niejszych wersji.
.PP
Niniejszy program rozpowszechniany jest z nadziej±, i¿ bêdzie on
u¿yteczny - jednak BEZ JAKIEJKOLWIEK GWARANCJI, nawet domy¶lnej
gwarancji PRZYDATNO¦CI HANDLOWEJ albo PRZYDATNO¦CI DO OKRE¦LONYCH
ZASTOSOWAÑ. W celu uzyskania bli¿szych informacji - Powszechna
Licencja Publiczna GNU.
.PP
Z pewno¶ci± wraz z niniejszym programem otrzyma³e¶ te¿ egzemplarz
Powszechnej Licencji Publicznej GNU; je¶li nie - napisz do Free
Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
MA  02111-1307  USA
.SH AUTOR
.ft CW
.nf
 __("<   Marcin Kowalczyk * qrczak@knm.org.pl http://qrczak.home.ml.org/
 \\__/       GCS/M d- s+:-- a21 C+++>+++$ UL++>++++$ P+++ L++>++++$ E->++
  ^^                W++ N+++ o? K? w(---) O? M- V? PS-- PE++ Y? PGP->+ t
QRCZAK                  5? X- R tv-- b+>++ DI D- G+ e>++++ h! r--%>++ y-
.fi
.ft R
