#!/bin/bash -

if [ "$FILTERM" = in ]
then
trs -e '
	\e[0\-9~\{U	U
	\e[0\-9~\{u	u
	\e[0\-90\-9~\{U	U
	\e[0\-90\-9~\{u	u
	^C		Ĉ
	^G		Ĝ
	^H		Ĥ
	^J		Ĵ
	^S		Ŝ
	^U		Ŭ
	~\{U		\177Ŭ
	^c		ĉ
	^g		ĝ
	^h		ĥ
	^j		ĵ
	^s		ŝ
	^u		ŭ
	~\{u		\177ŭ
	^^		^
'
else
trs -e '
	^C		Ĉ
	^G		Ĝ
	^H		Ĥ
	^J		Ĵ
	^S		Ŝ
	\[^~\]U		Ŭ
	^c		ĉ
	^g		ĝ
	^h		ĥ
	^j		ĵ
	^s		ŝ
	\[^~\]u		ŭ
'
fi
