#!/bin/bash -

TRS='
	€	Euro
	…	...
	‰	%%
	—	--
	™	(TM)
' TRS1='
	€	E
	‚	,
	„	÷
	…	.
	†	Å
	‡	Î
	‹	<
		"
	Ž	^
		,
	‘	`
	’	ï
	“	ò
	”	¦
	•	ù
	–	-
	—	-
	›	>
		-
	ž	,
	 	ÿ
	¢	–
	£	œ
	¤	Ÿ
	¦	§
	§	õ
	¨	
	©	¨
	ª	Š
	«	®
	¬	ª
	­	ð
	®	©
	¯	’
	°	ø
	±	ñ
	²	ý
	³	ü
	´	'\''
	µ	æ
	¶	ô
	·	ú
	¸	›
	¹	û
	º	‹
	»	¯
	¼	¬
	½	«
	¾	ó
	¿	‘
	À	µ
	Á	½
	Â	 
	Ã	€
	Ä	Ž
	Å	
	Æ	·
	Ç	í
	È	¶
	É	
	Ê	
	Ë	¸
	Ì	•
	Í	è
	Î	¡
	Ï	ê
	Ð	¾
	Ñ	ã
	Ò	î
	Ó	à
	Ô	â
	Õ	å
	Ö	™
	×	ž
	Ø	Æ
	Ù	­
	Ú	—
	Û	Ç
	Ü	š
	Ý	£
	Þ	Ï
	ß	á
	à	Ð
	á	Ô
	â	ƒ
	ã	‡
	ä	„
	å	†
	æ	Ò
	ç	‰
	è	Ñ
	é	‚
	ê	¥
	ë	Ó
	ì	…
	í	é
	î	Œ
	ï	ë
	ð	Õ
	ñ	ç
	ò	ì
	ó	¢
	ô	“
	õ	ä
	ö	”
	÷	ö
	ø	Ö
	ù	ˆ
	ú	˜
	û	×
	ü	
	ý	¤
	þ	Ø
	ÿ	.
\[‰™\] þ
' MIME=cp775 "${0%/*}/../aux/charset-charset" cp1257-cp775
