#!/bin/bash -

TRS='
	€	Euro
	…	...
	‰	%%
	—	--
	™	(TM)
	©	(c)
	®	(R)
	±	+-
	¶	P:
' TRS1='
	€	E
	‚	,
	ƒ	f
	„	"
	…	.
	†	Å
	‡	Î
	Š	æ
	‹	<
	Œ	—
		›
	Ž	¦
		
	‘	`
	’	'\''
	“	"
	”	"
	•	*
	–	-
	—	-
	š	ç
	›	>
	œ	˜
		œ
	ž	§
	Ÿ	«
	 	ÿ
	¡	ó
	¢	ô
	£	
	¤	Ï
	¥	¤
	¦	|
	§	õ
	¨	ù
	©	c
	ª	¸
	«	®
	¬	ª
	­	ð
	®	R
	¯	½
	°	ø
	²	ò
	³	ˆ
	´	ï
	µ	u
	¶	P
	·	.
	¸	÷
	¹	¥
	º	­
	»	¯
	¼	•
	½	ñ
	¾	–
	¿	¾
	À	è
	Á	µ
	Â	¶
	Ã	Æ
	Ä	Ž
	Å	‘
	Æ	
	Ç	€
	È	¬
	É	
	Ê	¨
	Ë	Ó
	Ì	·
	Í	Ö
	Î	×
	Ï	Ò
	Ð	Ñ
	Ñ	ã
	Ò	Õ
	Ó	à
	Ô	â
	Õ	Š
	Ö	™
	×	ž
	Ø	ü
	Ù	Þ
	Ú	é
	Û	ë
	Ü	š
	Ý	í
	Þ	Ý
	ß	á
	à	ê
	á	 
	â	ƒ
	ã	Ç
	ä	„
	å	’
	æ	†
	ç	‡
	è	Ÿ
	é	‚
	ê	©
	ë	‰
	ì	Ø
	í	¡
	î	Œ
	ï	Ô
	ð	Ð
	ñ	ä
	ò	å
	ó	¢
	ô	“
	õ	‹
	ö	”
	÷	ö
	ø	ý
	ù	…
	ú	£
	ü	
	ý	ì
	þ	î
	ÿ	ú
\[‰™±\] þ
' MIME=cp852 "${0%/*}/../aux/charset-charset" cp1250-cp852
