#!/bin/bash -

TRS='
	€	Euro
	…	...
	‰	%%
	Œ	OE
	—	--
	™	(TM)
	œ	oe
' TRS1='
	€	E
	‚	,
	ƒ	Ÿ
	„	"
	…	.
	†	Å
	‡	Î
	ˆ	^
	Š	S
	‹	<
	Ž	Z
	Œ	O
	‘	`
	’	'\''
	“	"
	”	"
	•	ú
	–	-
	—	-
	˜	~
	š	s
	›	>
	œ	o
	ž	z
	Ÿ	Y
	 	ÿ
	¡	­
	¢	½
	£	œ
	¤	Ï
	¥	¾
	¦	Ý
	§	õ
	¨	ù
	©	¸
	ª	¦
	«	®
	¬	ª
	­	ð
	®	©
	¯	î
	°	ø
	±	ñ
	²	ý
	³	ü
	´	ï
	µ	æ
	¶	ô
	·	ú
	¸	÷
	¹	û
	º	§
	»	¯
	¼	¬
	½	«
	¾	ó
	¿	¨
	À	·
	Á	µ
	Â	¶
	Ã	Ç
	Ä	Ž
	Å	
	Æ	’
	Ç	€
	È	Ô
	É	
	Ê	Ò
	Ë	Ó
	Ì	Þ
	Í	Ö
	Î	×
	Ï	Ø
	Ð	Ñ
	Ñ	¥
	Ò	ã
	Ó	à
	Ô	â
	Õ	å
	Ö	™
	×	ž
	Ø	
	Ù	ë
	Ú	é
	Û	ê
	Ü	š
	Ý	í
	Þ	è
	ß	á
	à	…
	á	 
	â	ƒ
	ã	Æ
	ä	„
	å	†
	æ	‘
	ç	‡
	è	Š
	é	‚
	ê	ˆ
	ë	‰
	ì	
	í	¡
	î	Œ
	ï	‹
	ð	Ð
	ñ	¤
	ò	•
	ó	¢
	ô	“
	õ	ä
	ö	”
	÷	ö
	ø	›
	ù	—
	ú	£
	û	–
	ü	
	ý	ì
	þ	ç
	ÿ	˜
\[‰™\] þ
' MIME=cp850 "${0%/*}/../aux/charset-charset" cp1252-cp850
