#!/bin/bash -

TRS='
	€	Euro
	…	...
	‡	++
	‰	%%
	Œ	OE
	—	--
	™	(TM)
	œ	oe
' TRS1='
	€	E
	‚	,
	ƒ	f
	„	"
	…	.
	†	+
	‡	+
	ˆ	^
	Š	S
	‹	<
	Œ	O
	‘	`
	’	'\''
	“	"
	”	"
	•	·
	–	-
	—	-
	˜	~
	š	s
	›	>
	œ	o
	Ÿ	Y
\[‰™\] ?
' MIME=iso-8859-9 "${0%/*}/../aux/charset-charset" cp1254-iso9
