#!/bin/bash -

TRS='
	…	...
	‡	++
	ˆ	Euro
	‰	%%
	—	--
	™	(TM)
	¤	CUR
	©	(c)
	«	<<
	®	(R)
	±	+-
	¶	P:
	»	>>
' TRS1='
	€	¢
		£
	‚	,
	ƒ	ó
	„	"
	…	.
	†	+
	‡	+
	ˆ	E
	Š	©
	‹	<
	Œ	ª
		¬
	Ž	«
		¯
		ò
	‘	`
	’	'\''
	“	"
	”	"
	•	*
	–	-
	—	-
	š	ù
	›	>
	œ	ú
		ü
	ž	û
	Ÿ	ÿ
	¡	®
	¢	þ
	£	¨
	¤	*
	¥	³
	¦	|
	§	ý
	¨	¡
	©	c
	ª	¤
	«	<
	¬	~
	®	R
	¯	§
	°	o
	²	¦
	³	ö
	´	Ó
	µ	u
	¶	P
	·	.
	¸	ñ
	¹	ð
	º	ô
	»	>
	¼	ø
	½	¥
	¾	õ
	¿	÷
	À	°
	Á	±
	Â	²
	Ã	³
	Ä	´
	Å	µ
	Æ	¶
	Ç	·
	È	¸
	É	¹
	Ê	º
	Ë	»
	Ì	¼
	Í	½
	Î	¾
	Ï	¿
	Ð	À
	Ñ	Á
	Ò	Â
	Ó	Ã
	Ô	Ä
	Õ	Å
	Ö	Æ
	×	Ç
	Ø	È
	Ù	É
	Ú	Ê
	Û	Ë
	Ü	Ì
	Ý	Í
	Þ	Î
	ß	Ï
	à	Ð
	á	Ñ
	â	Ò
	ã	Ó
	ä	Ô
	å	Õ
	æ	Ö
	ç	×
	è	Ø
	é	Ù
	ê	Ú
	ë	Û
	ì	Ü
	í	Ý
	î	Þ
	ï	ß
	ð	à
	ñ	á
	ò	â
	ó	ã
	ô	ä
	õ	å
	ö	æ
	÷	ç
	ø	è
	ù	é
	ú	ê
	û	ë
	ü	ì
	ý	í
	þ	î
	ÿ	ï
\[‰™±\] ?
' MIME=iso-8859-5 "${0%/*}/../aux/charset-charset" cp1251-iso5
