#!/bin/bash -

VARIANT_de='
	ü	ue
' VARIANT_vi='
	à	a`
	â	a^
	è	e`
	é	e'\''
	ê	e^
	ô	o^
	ù	u`
' TRS='
	€	Euro
	…	...
	‡	++
	‰	%%
	Œ	OE
	—	--
	™	(TM)
	œ	oe
		\!
	ž	\!
	§	S:
	©	(c)
	«	<<
	®	(R)
	±	+-
	²	^2
	³	^3
	¶	P:
	¹	^1
	»	>>
	¼	\s1/4
	½	\s1/2
	¾	\s3/4
	ý	[->]
	þ	[<-]
' TRS1='
	€	E
	‚	,
	ƒ	f
	„	"
	…	.
	†	+
	‡	+
	ˆ	^
	‹	<
	Œ	O
	‘	`
	’	'\''
	“	"
	”	"
	•	*
	–	-
	—	-
	›	>
	œ	o
		\s
	ž	\s
	¡	¬
	¢	c
	£	L
	¥	Y
	¦	|
	§	S
	¨	"
	©	c
	«	<
	¬	~
	®	R
	¯	-
	°	o
	²	2
	³	3
	´	'\''
	µ	u
	¶	P
	·	.
	¸	,
	¹	1
	º	»
	»	>
	¼	/
	½	/
	¾	/
	×	x
	Ø	×
	Ù	Ø
	Ú	Ù
	Û	Ú
	Ü	à
	Ý	á
	Þ	â
	ß	ã
	à	a
	á	ä
	â	a
	ã	å
	ä	æ
	å	ç
	æ	è
	ç	c
	è	e
	é	e
	ê	e
	ë	e
	ì	é
	í	ê
	î	i
	ï	i
	ð	ë
	ñ	ì
	ò	í
	ó	î
	ô	o
	õ	ï
	ö	ð
	÷	:
	ø	ñ
	ù	u
	ú	ò
	û	u
	ü	u
	ý	>
	þ	<
\[‰Ž™±\] ?
' MIME=iso-8859-6 "${0%/*}/../aux/charset-charset" cp1256-iso6
