#!/bin/bash -

TRS='
	€	DJ
	…	...
	ˆ	Euro
	‰	%%
	Š	‹œ
	Œ	œ
	Ž	TSH
		DZ
		dj
	—	--
	™	(TM)
	š	«ì
	œ	­ì
	ž	tsh
	Ÿ	dz
	§	S:
	©	(c)
	«	<<
	­	\!
	®	(R)
	±	+-
	¶	P:
	»	>>
' TRS1='
	€	D
		ƒ
	‚	,
	ƒ	£
	„	"
	…	.
	†	Å
	‡	Ø
	ˆ	E
	Š	‹
	‹	<
	Œ	
		Š
	Ž	C
		d
	‘	`
	’	'\''
	“	"
	”	"
	•	ù
	–	-
	—	-
	š	«
	›	>
	œ	­
		ª
	ž	c
	 	ÿ
	¡	ö
	¢	÷
	£	J
	¤	ý
	¥	ƒ
	¦	|
	§	S
	¨	ð
	©	c
	ª	ò
	«	<
	¬	~
	­	-
	®	R
	¯	ô
	°	ø
	²	I
	³	i
	´	£
	µ	u
	¶	P
	·	ú
	¸	ñ
	¹	ü
	º	ó
	»	>
	¼	j
	½	S
	¾	s
	¿	õ
	À	€
	Á	
	Â	‚
	Ã	ƒ
	Ä	„
	Å	…
	Æ	†
	Ç	‡
	È	ˆ
	É	‰
	Ê	Š
	Ë	‹
	Ì	Œ
	Í	
	Î	Ž
	Ï	
	Ð	
	Ñ	‘
	Ò	’
	Ó	“
	Ô	”
	Õ	•
	Ö	–
	×	—
	Ø	˜
	Ù	™
	Ú	š
	Û	›
	Ü	œ
	Ý	
	Þ	ž
	ß	Ÿ
	à	 
	á	¡
	â	¢
	ã	£
	ä	¤
	å	¥
	æ	¦
	ç	§
	è	¨
	é	©
	ê	ª
	ë	«
	ì	¬
	í	­
	î	®
	ï	¯
	ð	à
	ñ	á
	ò	â
	ó	ã
	ô	ä
	õ	å
	ö	æ
	÷	ç
	ø	è
	ù	é
	ú	ê
	û	ë
	ü	ì
	ý	í
	þ	î
	ÿ	ï
\[‰™Ÿ±\] þ
' MIME=cp866 "${0%/*}/../aux/charset-charset" cp1251-cp866
