#!/bin/bash -

TRS='
	‡	++
	ˆ	Euro
	‰	%%
	­	\!
' TRS1='
	€	«
		®
	‚	,
	ƒ	¯
	„	×
	…	É
	†	 
	‡	+
	ˆ	E
	Š	¼
	‹	<
	Œ	¾
		Í
	Ž	Ë
		Ú
		¬
	‘	Ô
	’	Õ
	“	Ò
	”	Ó
	•	¥
	–	Ð
	—	Ñ
	™	ª
	š	½
	›	>
	œ	¿
		Î
	ž	Ì
	Ÿ	Û
	 	Ê
	¡	Ø
	¢	Ù
	£	·
	¤	ÿ
	¥	¢
	¦	|
	§	¤
	¨	Ý
	ª	¸
	«	Ç
	¬	Â
	­	-
	®	¨
	¯	º
	°	¡
	²	§
	³	´
	´	¶
	¶	¦
	·	¥
	¸	Þ
	¹	Ü
	º	¹
	»	È
	¼	À
	½	Á
	¾	Ï
	¿	»
	À	€
	Á	
	Â	‚
	Ã	ƒ
	Ä	„
	Å	…
	Æ	†
	Ç	‡
	È	ˆ
	É	‰
	Ê	Š
	Ë	‹
	Ì	Œ
	Í	
	Î	Ž
	Ï	
	Ð	
	Ñ	‘
	Ò	’
	Ó	“
	Ô	”
	Õ	•
	Ö	–
	×	—
	Ø	˜
	Ù	™
	Ú	š
	Û	›
	Ü	œ
	Ý	
	Þ	ž
	ß	Ÿ
	ÿ	ß
\[‰\] ?
' MIME=x-maccyr "${0%/*}/../aux/charset-charset" cp1251-maccyr
