#!/bin/bash -

TRS='
	€	Euro
	…	...
	‡	++
	‰	%%
	™	(TM)
	¤	CUR
	®	(R)
	¶	P:
' TRS1='
	€	E
	‚	,
	ƒ	f
	„	"
	…	.
	†	+
	‡	+
	‹	<
	‘	`
	’	'\''
	“	"
	”	"
	•	·
	–	-
	—	¯
	›	>
	¡	µ
	¢	¶
	¤	*
	¥	Y
	®	R
	µ	ì
	¶	P
\[‰™\] ?
' MIME=iso-8859-7 "${0%/*}/../aux/charset-charset" cp1253-iso7
