#!/bin/bash -

TRS='
	€	Euro
	…	...
	‰	%%
	—	--
	™	(TM)
	¤	CUR
	§	S:
	©	(c)
	«	<<
	­	\!
	®	(R)
	¯	--
	³	^3
	¶	P:
	»	>>
	½	\s1/2
' TRS1='
	€	E
	‚	,
	ƒ	f
	„	"
	…	.
	†	Å
	‡	Ø
	‹	<
	‘	`
	’	'\''
	“	"
	”	"
	•	ù
	–	-
	—	-
	›	>
	 	ÿ
	¡	"
	¢	ê
	£	L
	¤	*
	¥	Y
	¦	|
	§	S
	¨	"
	©	c
	«	<
	¬	~
	­	-
	®	R
	¯	-
	°	ø
	±	ñ
	²	ý
	³	3
	´	'\''
	µ	£
	¶	P
	·	ú
	¸	ë
	¹	ì
	º	í
	»	>
	¼	î
	½	/
	¾	ï
	¿	ð
	À	i
	Á	€
	Â	
	Ã	‚
	Ä	ƒ
	Å	„
	Æ	…
	Ç	†
	È	‡
	É	ˆ
	Ê	‰
	Ë	Š
	Ì	‹
	Í	Œ
	Î	
	Ï	Ž
	Ð	
	Ñ	
	Ó	‘
	Ô	’
	Õ	“
	Ö	”
	×	•
	Ø	–
	Ù	—
	Ú	ô
	Û	õ
	Ü	á
	Ý	â
	Þ	ã
	ß	å
	à	u
	á	˜
	â	™
	ã	š
	ä	›
	å	œ
	æ	
	ç	ž
	è	Ÿ
	é	 
	ê	¡
	ë	¢
	ì	£
	í	¤
	î	¥
	ï	¦
	ð	§
	ñ	¨
	ò	ª
	ó	©
	ô	«
	õ	¬
	ö	­
	÷	®
	ø	¯
	ù	à
	ú	ä
	û	è
	ü	æ
	ý	ç
	þ	é
\[‰™\] þ
' MIME=cp737 "${0%/*}/../aux/charset-charset" cp1253-cp737
