#!/bin/bash -

TRS='
	€	Euro
	¤	CUR
	­	\!
	²	^2
	³	^3
	¹	^1
	¼	\s1/4
	½	\s1/2
	¾	\s3/4
' TRS1='
	€	E
	‚	â
	ƒ	Ä
	„	ã
	…	É
	†	 
	‡	à
	ˆ	ö
	‰	ä
	Š	S
	‹	<
	Œ	Î
	‘	Ô
	’	Õ
	“	Ò
	”	Ó
	•	¥
	–	Ð
	—	Ñ
	˜	÷
	™	ª
	š	s
	›	>
	œ	Ï
	Ÿ	Ù
	 	Ê
	¡	Á
	¤	*
	¥	´
	¦	|
	§	¤
	¨	¬
	ª	»
	«	Ç
	¬	Â
	­	-
	®	¨
	¯	ø
	°	¡
	²	2
	³	3
	´	«
	¶	¦
	·	á
	¸	ü
	¹	1
	º	¼
	»	È
	¼	/
	½	/
	¾	/
	¿	À
	À	Ë
	Á	ç
	Â	å
	Ã	Ì
	Ä	€
	Å	
	Æ	®
	Ç	‚
	È	é
	É	ƒ
	Ê	æ
	Ë	è
	Ì	í
	Í	ê
	Î	ë
	Ï	ì
	Ð	Ú
	Ñ	„
	Ò	ñ
	Ó	î
	Ô	ï
	Õ	Í
	Ö	…
	×	x
	Ø	¯
	Ù	ô
	Ú	ò
	Û	ó
	Ü	†
	Ý	Ü
	ß	§
	à	ˆ
	á	‡
	â	‰
	ã	‹
	ä	Š
	å	Œ
	æ	¾
	ç	
	è	
	é	Ž
	ê	
	ë	‘
	ì	“
	í	’
	î	”
	ï	•
	ð	Û
	ñ	–
	ò	˜
	ó	—
	ô	™
	õ	›
	ö	š
	÷	Ö
	ø	¿
	ù	
	ú	œ
	û	ž
	ü	Ÿ
	ý	Ý
	þ	ß
	ÿ	Ø
' MIME=x-mactur "${0%/*}/../aux/charset-charset" cp1254-mactur
