#!/bin/bash -

TRS='
	ž	Pts
	«	\s1/2
	¬	\s1/4
	è	PH
	é	TH
	ê	OH
	í	ph
	ð	==
	ü	^n
	ý	^2
' TRS1='
	€	‚
		Ÿ
	‚	Ž
	ƒ	‰
	„	Š
	…	ˆ
	†	Œ
	‡	
	ˆ	
	‰	‘
	Š	
	‹	•
	Œ	”
		“
	Ž	€
		
		ƒ
	‘	¾
	’	®
	“	™
	”	š
	•	˜
	–	ž
	—	
	˜	Ø
	™	…
	š	†
	›	¢
	œ	£
		´
	ž	P
	Ÿ	Ä
	 	‡
	¡	’
	¢	—
	£	œ
	¤	–
	¥	„
	¦	»
	§	¼
	¨	À
	©	Â
	ª	Â
	«	/
	¬	/
	­	Á
	®	Ç
	¯	È
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	|
	¶	|
	·	+
	¸	+
	¹	|
	º	|
	»	+
	¼	+
	½	+
	¾	+
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	|
	Ç	|
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	=
	Ð	-
	Ñ	=
	Ò	-
	Ó	+
	Ô	+
	Õ	+
	Ö	+
	×	|
	Ø	|
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	[
	Þ	]
	ß	"
	à	a
	á	§
	â	G
	ã	¹
	ä	S
	å	s
	æ	µ
	ç	t
	è	F
	é	T
	ê	O
	ë	d
	ì	°
	í	f
	î	e
	ï	*
	ð	=
	ñ	±
	ò	³
	ó	²
	ô	/
	õ	/
	ö	Ö
	÷	Å
	ø	¡
	ù	¥
	ú	á
	û	Ã
	ü	n
	ý	2
	þ	\#
	ÿ	Ê
' MIME=x-mac "${0%/*}/../aux/charset-charset" cp437-mac
