#!/bin/bash -

TRS='
	û	SQRT\s
	ü	^n
' TRS1='
	€	°
		µ
	‚	¡
	ƒ	¢
	„	¶
	…	·
	†	¸
	‡	£
	ˆ	¹
	‰	º
	Š	¤
	‹	»
	Œ	Á
		¥
	Ž	Ã
		¦
		Ä
	‘	ª
	’	Æ
	“	Ë
	”	¼
	•	Ì
	–	¾
	—	¿
	˜	á
	™	â
	š	ç
	›	ä
	œ	å
		ú
	ž	è
	Ÿ	õ
	 	é
	¡	ë
	¢	ì
	£	í
	¤	î
	¥	ê
	¦	ï
	§	ð
	¨	ò
	©	ó
	ª	÷
	«	ô
	¬	ù
	­	æ
	®	ø
	¯	ã
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	|
	¶	|
	·	+
	¸	+
	¹	|
	º	|
	»	+
	¼	+
	½	+
	¾	+
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	|
	Ç	|
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	=
	Ð	-
	Ñ	=
	Ò	-
	Ó	+
	Ô	+
	Õ	+
	Ö	+
	×	|
	Ø	|
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	[
	Þ	]
	ß	"
	à	ö
	á	À
	â	Û
	ã	Ü
	ä	û
	å	Ý
	æ	Þ
	ç	à
	è	ü
	é	ñ
	ê	Í
	ë	Î
	ì	×
	í	Ø
	î	Ù
	ï	Ú
	ð	ß
	ñ	±
	ò	³
	ó	²
	ô	«
	õ	½
	ö	Ö
	÷	Å
	ø	®
	ù	–
	ú	–
	û	V
	ü	n
	ý	‚
	þ	\#
	ÿ	Ê
' MIME=x-macgreek "${0%/*}/../aux/charset-charset" cp737-macgreek
