#!/bin/bash -

VARIANT_vi='
	¢	o'\''
	à	O'\''
' TRS='
	¨	(c)
	©	(R)
	«	\s1/2
	¬	\s1/4
	®	<<
	¯	>>
	ñ	+-
	ó	\s3/4
	ô	P:
	û	^1
	ü	^3
	ý	^2
' TRS1='
	€	C
		ü
	‚	é
	ƒ	à
	„	ä
	…	»
	†	å
	‡	c
	ˆ	l
	‰	º
	Š	£
	‹	³
	Œ	ï
		Z
	Ž	Ä
		Å
		É
	‘	æ
	’	Æ
	“	ò
	”	ö
	•	«
	–	c
	—	S
	˜	s
	™	Ö
	š	Ü
	›	ø
	œ	L
		Ø
	ž	×
	Ÿ	¤
	 	À
	¡	Ï
	¢	o
	£	Z
	¤	z
	¥	z
	¦	"
	§	|
	¨	c
	©	R
	ª	~
	«	/
	¬	/
	­	L
	®	<
	¯	>
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	¡
	¶	È
	·	Ê
	¸	Ì
	¹	|
	º	|
	»	+
	¼	+
	½	Ç
	¾	©
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	Ù
	Ç	Þ
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	®
	Ð	±
	Ñ	è
	Ò	ê
	Ó	ì
	Ô	ç
	Õ	¹
	Ö	ù
	×	þ
	Ø	¾
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	[
	Þ	]
	ß	"
	à	O
	á	ß
	â	Ò
	ã	N
	ä	õ
	å	Õ
	æ	u
	ç	n
	è	Ó
	é	ó
	ê	¦
	ë	¶
	ì	ñ
	í	ª
	î	Ñ
	ï	'\''
	ð	­
	ò	"
	ó	/
	ô	P
	õ	§
	ö	÷
	÷	"
	ø	°
	ù	*
	ú	.
	û	1
	ü	3
	ý	2
	þ	\#
	ÿ	 
\[ñ\] ?
' MIME=iso-8859-4 "${0%/*}/../aux/charset-charset" cp775-iso4
