#!/bin/bash -

TRS='
' TRS1='
	€	Ã
		ü
	‚	é
	ƒ	â
	„	ä
	…	ì
	†	å
	‡	ã
	ˆ	ù
	‰	ç
	Š	ª
	‹	º
	Œ	î
		Ê
	Ž	Ä
		Å
		É
	‘	¿
	’	¯
	“	ô
	”	ö
	•	Ì
	–	¢
	—	Ú
	˜	ú
	™	Ö
	š	Ü
	›	¸
	œ	£
		¨
	ž	×
	Ÿ	¤
	 	Â
	¡	Î
	¢	ó
	£	Ý
	¤	ý
	¥	ê
	¦	”
	§	¦
	¨	©
	©	®
	ª	¬
	«	½
	¬	¼
	­	Ù
	®	«
	¯	»
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	À
	¶	È
	·	Æ
	¸	Ë
	¹	|
	º	|
	»	+
	¼	+
	½	Á
	¾	Ð
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	Ø
	Ç	Û
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	Þ
	Ð	à
	Ñ	è
	Ò	æ
	Ó	ë
	Ô	á
	Õ	ð
	Ö	ø
	×	û
	Ø	þ
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	[
	Þ	]
	ß	"
	à	Ó
	á	ß
	â	Ô
	ã	Ñ
	ä	õ
	å	Õ
	æ	µ
	ç	ñ
	è	Í
	é	í
	ê	Ï
	ë	ï
	ì	ò
	í	Ç
	î	Ò
	ï	’
	ð	­
	ñ	±
	ò	“
	ó	¾
	ô	¶
	õ	§
	ö	÷
	÷	„
	ø	°
	ù	•
	ú	·
	û	¹
	ü	³
	ý	²
	þ	\#
	ÿ	 
' MIME=windows-1257 "${0%/*}/../aux/charset-charset" cp775-cp1257
