#!/bin/bash -

TRS='
	«	\s1/2
	¬	\s1/4
	Ï	CUR
	ð	\!
	ó	\s3/4
	û	^1
	ü	^3
	ý	^2
' TRS1='
	€	‚
		Ÿ
	‚	Ž
	ƒ	‰
	„	Š
	…	ˆ
	†	Œ
	‡	
	ˆ	
	‰	‘
	Š	
	‹	•
	Œ	”
		Ý
	Ž	€
		
		ƒ
	‘	¾
	’	®
	“	™
	”	š
	•	˜
	–	ž
	—	
	˜	Ü
	™	…
	š	†
	›	¿
	œ	£
		¯
	ž	Þ
	Ÿ	ß
	 	‡
	¡	’
	¢	—
	£	œ
	¤	–
	¥	„
	¦	Ú
	§	Û
	¨	À
	©	¨
	ª	Â
	«	/
	¬	/
	­	Á
	®	Ç
	¯	È
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	ç
	¶	å
	·	Ë
	¸	©
	¹	|
	º	|
	»	+
	¼	+
	½	¢
	¾	´
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	‹
	Ç	Ì
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	*
	Ð	¼
	Ñ	»
	Ò	æ
	Ó	è
	Ô	é
	Ö	ê
	×	ë
	Ø	ì
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	|
	Þ	í
	ß	"
	à	î
	á	§
	â	ï
	ã	ñ
	ä	›
	å	Í
	æ	µ
	è	x
	é	ò
	ê	ó
	ë	ô
	ì	“
	í	Ø
	î	ø
	ï	«
	ð	-
	ñ	±
	ó	/
	ô	¦
	õ	¤
	ö	Ö
	÷	ü
	ø	¡
	ù	¬
	ú	á
	û	1
	ü	3
	ý	2
	þ	\#
	ÿ	Ê
' MIME=x-mactur "${0%/*}/../aux/charset-charset" cp857-mactur
