#!/bin/bash -

TRS='
	®	<<
	¯	>>
' TRS1='
	€	Ç
		ü
	‚	é
	ƒ	â
	„	ä
	…	ù
	†	æ
	‡	ç
	ˆ	³
	‰	ë
	Š	Õ
	‹	õ
	Œ	î
		¬
	Ž	Ä
		Æ
		É
	‘	Å
	’	å
	“	ô
	”	ö
	•	¥
	–	µ
	—	¦
	˜	¶
	™	Ö
	š	Ü
	›	«
	œ	»
		£
	ž	×
	Ÿ	è
	 	á
	¡	í
	¢	ó
	£	ú
	¤	¡
	¥	±
	¦	®
	§	¾
	¨	Ê
	©	ê
	ª	~
	«	¼
	¬	È
	­	º
	®	<
	¯	>
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	Á
	¶	Â
	·	Ì
	¸	ª
	¹	|
	º	|
	»	+
	¼	+
	½	¯
	¾	¿
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	Ã
	Ç	ã
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	¤
	Ð	ð
	Ñ	Ð
	Ò	Ï
	Ó	Ë
	Ô	ï
	Õ	Ò
	Ö	Í
	×	Î
	Ø	ì
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	Þ
	Þ	Ù
	ß	"
	à	Ó
	á	ß
	â	Ô
	ã	Ñ
	ä	ñ
	å	ò
	æ	©
	ç	¹
	è	À
	é	Ú
	ê	à
	ë	Û
	ì	ý
	í	Ý
	î	þ
	ï	´
	ð	­
	ñ	½
	ò	²
	ó	·
	ô	¢
	õ	§
	ö	÷
	÷	¸
	ø	°
	ù	¨
	ú	ÿ
	ü	Ø
	ý	ø
	þ	\#
	ÿ	 
' MIME=iso-8859-2 "${0%/*}/../aux/charset-charset" cp852-iso2
