#!/bin/bash -

TRS='
' TRS1='
	€	Ç
		ü
	‚	é
	ƒ	â
	„	ä
	…	à
	†	å
	‡	ç
	ˆ	ê
	‰	ë
	Š	è
	‹	ï
	Œ	î
		ý
	Ž	Ä
		Å
		É
	‘	æ
	’	Æ
	“	ô
	”	ö
	•	ò
	–	û
	—	ù
	˜	Ý
	™	Ö
	š	Ü
	›	ø
	œ	£
		Ø
	ž	Þ
	Ÿ	þ
	 	á
	¡	í
	¢	ó
	£	ú
	¤	ñ
	¥	Ñ
	¦	Ð
	§	ð
	¨	¿
	©	®
	ª	¬
	«	½
	¬	¼
	­	¡
	®	«
	¯	»
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	Á
	¶	Â
	·	À
	¸	©
	¹	|
	º	|
	»	+
	¼	+
	½	¢
	¾	¥
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	ã
	Ç	Ã
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	¤
	Ð	º
	Ñ	ª
	Ò	Ê
	Ó	Ë
	Ô	È
	Ö	Í
	×	Î
	Ø	Ï
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	¦
	Þ	Ì
	ß	"
	à	Ó
	á	ß
	â	Ô
	ã	Ò
	ä	õ
	å	Õ
	æ	µ
	è	×
	é	Ú
	ê	Û
	ë	Ù
	í	ÿ
	î	¯
	ï	´
	ð	­
	ñ	±
	ó	¾
	ô	¶
	õ	§
	ö	÷
	÷	¸
	ø	°
	ù	¨
	ú	·
	û	¹
	ü	³
	ý	²
	þ	\#
	ÿ	 
' MIME=windows-1254 "${0%/*}/../aux/charset-charset" cp857-cp1254
