#!/bin/bash -

VARIANT_hr='
	Ð	dj
	Ñ	DJ
' VARIANT_vi='
	ƒ	a^
	¶	A^
	Æ	A(
	Ç	a(
	Ð	dd
	Ñ	DD
' TRS='
	Ï	CUR
	ð	\!
' TRS1='
	€	C
		Ÿ
	‚	Ž
	ƒ	a
	„	Š
	…	ó
	†	
	‡	c
	ˆ	¸
	‰	e
	Š	Ì
	‹	Î
	Œ	i
		
	Ž	€
		Œ
		ƒ
	‘	½
	’	¾
	“	™
	”	š
	•	»
	–	¼
	—	å
	˜	æ
	™	…
	š	†
	›	è
	œ	é
		ü
	ž	x
	Ÿ	‹
	 	‡
	¡	’
	¢	—
	£	œ
	¤	„
	¥	ˆ
	¦	ë
	§	ì
	¨	¢
	©	«
	ª	Â
	«	
	¬	‰
	­	s
	®	Ç
	¯	È
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	ç
	¶	A
	·	
	¸	S
	¹	|
	º	|
	»	+
	¼	+
	½	û
	¾	ý
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	A
	Ç	a
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	*
	Ð	d
	Ñ	D
	Ò	‘
	Ó	E
	Ô	“
	Õ	Å
	Ö	ê
	×	I
	Ø	ž
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	T
	Þ	ñ
	ß	"
	à	î
	á	§
	â	ï
	ã	Á
	ä	Ä
	å	Ë
	æ	á
	ç	ä
	è	Ù
	é	ò
	ê	Ú
	ë	ô
	ì	ù
	í	ø
	î	t
	ï	'\''
	ð	-
	ñ	"
	ò	,
	ó	ÿ
	ô	~
	õ	¤
	ö	Ö
	÷	,
	ø	¡
	ù	¬
	ú	.
	û	õ
	ü	Û
	ý	Þ
	þ	\#
	ÿ	Ê
' MIME=x-macce "${0%/*}/../aux/charset-charset" cp852-macce
