#!/bin/bash -

TRS='
	û	SQRT\s
' TRS1='
	€	À
		Á
	‚	Â
	ƒ	Ã
	„	Ä
	…	Å
	†	Æ
	‡	Ç
	ˆ	È
	‰	É
	Š	Ê
	‹	Ë
	Œ	Ì
		Í
	Ž	Î
		Ï
		Ð
	‘	Ñ
	’	Ò
	“	Ó
	”	Ô
	•	Õ
	–	Ö
	—	×
	˜	Ø
	™	Ù
	š	Ú
	›	Û
	œ	Ü
		Ý
	ž	Þ
	Ÿ	ß
	 	à
	¡	á
	¢	â
	£	ã
	¤	ä
	¥	å
	¦	æ
	§	ç
	¨	è
	©	é
	ª	ê
	«	ë
	¬	ì
	­	í
	®	î
	¯	ï
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	|
	¶	|
	·	+
	¸	+
	¹	|
	º	|
	»	+
	¼	+
	½	+
	¾	+
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	|
	Ç	|
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	=
	Ð	-
	Ñ	=
	Ò	-
	Ó	+
	Ô	+
	Õ	+
	Ö	+
	×	|
	Ø	|
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	[
	Þ	]
	ß	"
	à	ð
	á	ñ
	â	ò
	ã	ó
	ä	ô
	å	õ
	æ	ö
	ç	÷
	è	ø
	é	ù
	ê	ú
	ë	û
	ì	ü
	í	ý
	î	þ
	ï	ÿ
	ð	¨
	ñ	¸
	ò	ª
	ó	º
	ô	¯
	õ	¿
	ö	¡
	÷	¢
	ø	°
	ù	•
	ú	·
	û	V
	ü	¹
	ý	¤
	þ	\#
	ÿ	 
' MIME=windows-1251 "${0%/*}/../aux/charset-charset" cp866-cp1251
