#!/bin/bash -

TRS='
	û	SQRT\s
	ý	CUR
' TRS1='
	€	°
		±
	‚	²
	ƒ	³
	„	´
	…	µ
	†	¶
	‡	·
	ˆ	¸
	‰	¹
	Š	º
	‹	»
	Œ	¼
		½
	Ž	¾
		¿
		À
	‘	Á
	’	Â
	“	Ã
	”	Ä
	•	Å
	–	Æ
	—	Ç
	˜	È
	™	É
	š	Ê
	›	Ë
	œ	Ì
		Í
	ž	Î
	Ÿ	Ï
	 	Ð
	¡	Ñ
	¢	Ò
	£	Ó
	¤	Ô
	¥	Õ
	¦	Ö
	§	×
	¨	Ø
	©	Ù
	ª	Ú
	«	Û
	¬	Ü
	­	Ý
	®	Þ
	¯	ß
	°	\#
	±	\#
	²	\#
	³	|
	´	|
	µ	|
	¶	|
	·	+
	¸	+
	¹	|
	º	|
	»	+
	¼	+
	½	+
	¾	+
	¿	+
	À	+
	Á	-
	Â	-
	Ã	|
	Ä	-
	Å	|
	Æ	|
	Ç	|
	È	+
	É	+
	Ê	=
	Ë	=
	Ì	|
	Í	=
	Î	|
	Ï	=
	Ð	-
	Ñ	=
	Ò	-
	Ó	+
	Ô	+
	Õ	+
	Ö	+
	×	|
	Ø	|
	Ù	+
	Ú	+
	Û	\#
	Ü	_
	Ý	[
	Þ	]
	ß	"
	ð	¡
	ò	¤
	ó	ô
	ô	§
	õ	÷
	ö	®
	÷	þ
	ø	o
	ù	*
	ú	.
	û	V
	ü	ð
	ý	*
	þ	\#
	ÿ	 
' MIME=iso-8859-5 "${0%/*}/../aux/charset-charset" cp866-iso5
