#!/bin/bash -

VARIANT_vi='
	Ý	Y'\''
	ý	y'\''
' TRS='
	­	\!
	²	^2
	³	^3
	¹	^1
	¼	\s1/4
	½	\s1/2
	¾	\s3/4
	Ð	DH
	Þ	TH
	ð	dh
	þ	th
' TRS1='
	 	Ê
	¡	Á
	¤	Û
	¥	´
	¦	|
	§	¤
	¨	¬
	ª	»
	«	Ç
	¬	Â
	­	-
	®	¨
	¯	ø
	°	¡
	²	2
	³	3
	´	«
	¶	¦
	·	á
	¸	ü
	¹	1
	º	¼
	»	È
	¼	/
	½	/
	¾	/
	¿	À
	À	Ë
	Á	ç
	Â	å
	Ã	Ì
	Ä	€
	Å	
	Æ	®
	Ç	‚
	È	é
	É	ƒ
	Ê	æ
	Ë	è
	Ì	í
	Í	ê
	Î	ë
	Ï	ì
	Ð	D
	Ñ	„
	Ò	ñ
	Ó	î
	Ô	ï
	Õ	Í
	Ö	…
	×	x
	Ø	¯
	Ù	ô
	Ú	ò
	Û	ó
	Ü	†
	Ý	Y
	Þ	T
	ß	§
	à	ˆ
	á	‡
	â	‰
	ã	‹
	ä	Š
	å	Œ
	æ	¾
	ç	
	è	
	é	Ž
	ê	
	ë	‘
	ì	“
	í	’
	î	”
	ï	•
	ð	d
	ñ	–
	ò	˜
	ó	—
	ô	™
	õ	›
	ö	š
	÷	Ö
	ø	¿
	ù	
	ú	œ
	û	ž
	ü	Ÿ
	ý	y
	þ	t
	ÿ	Ø
\[€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ\] ?
' MIME=x-mac "${0%/*}/../aux/charset-charset" iso1-mac
