#!/bin/bash -

TRS='
	¤	CUR
	­	\!
' TRS1='
	 	\s
	¤	*
	­	-
\[0123456789€‚ƒ„…†‡‰‹‘’“”•–—™›¬»ΏΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡÒΣΤΥΦΧΨΩΪΰαβγδεζηθικλμνξοπρς\] ?
' MIME=us-ascii "${0%/*}/../aux/charset-charset" iso6-ascii
