#!/bin/bash -

TRS='
	§	S:
	©	(c)
	«	<<
	­	\!
	¯	--
	³	^3
	»	>>
	½	\s1/2
' TRS1='
	 	ÿ
	£	L
	¦	|
	§	S
	¨	"
	©	c
	«	<
	¬	~
	­	-
	¯	-
	°	ø
	±	ñ
	²	ý
	³	3
	´	'\''
	µ	"
	¶	ê
	·	ú
	¸	ë
	¹	ì
	º	í
	»	>
	¼	î
	½	/
	¾	ï
	¿	ð
	À	i
	Á	€
	Â	
	Ã	‚
	Ä	ƒ
	Å	„
	Æ	…
	Ç	†
	È	‡
	É	ˆ
	Ê	‰
	Ë	Š
	Ì	‹
	Í	Œ
	Î	
	Ï	Ž
	Ð	
	Ñ	
	Ó	‘
	Ô	’
	Õ	“
	Ö	”
	×	•
	Ø	–
	Ù	—
	Ú	ô
	Û	õ
	Ü	á
	Ý	â
	Þ	ã
	ß	å
	à	u
	á	˜
	â	™
	ã	š
	ä	›
	å	œ
	æ	
	ç	ž
	è	Ÿ
	é	 
	ê	¡
	ë	¢
	ì	£
	í	¤
	î	¥
	ï	¦
	ð	§
	ñ	¨
	ò	ª
	ó	©
	ô	«
	õ	¬
	ö	­
	÷	®
	ø	¯
	ù	à
	ú	ä
	û	è
	ü	æ
	ý	ç
	þ	é
\[€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ¡¢\] þ
' MIME=cp737 "${0%/*}/../aux/charset-charset" iso7-cp737
