#!/bin/bash -

TRS='
	¤	CUR
	§	S:
	©	(c)
	­	\!
	®	(R)
	³	^3
	¶	P:
	¹	^1
	¾	\s3/4
' TRS1='
	 	ÿ
	¢	›
	£	œ
	¤	*
	¥	
	¦	|
	§	S
	¨	"
	©	c
	ª	x
	«	®
	¬	ª
	­	-
	®	R
	¯	-
	°	ø
	±	ñ
	²	ý
	³	3
	´	'\''
	µ	æ
	¶	P
	·	ú
	¸	,
	¹	1
	º	ö
	»	¯
	¼	¬
	½	«
	¾	/
	ß	_
	à	€
	á	
	â	‚
	ã	ƒ
	ä	„
	å	…
	æ	†
	ç	‡
	è	ˆ
	é	‰
	ê	Š
	ë	‹
	ì	Œ
	í	
	î	Ž
	ï	
	ð	
	ñ	‘
	ò	’
	ó	“
	ô	”
	õ	•
	ö	–
	÷	—
	ø	˜
	ù	™
	ú	š
\[€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ\] þ
' MIME=cp862 "${0%/*}/../aux/charset-charset" iso8-cp862
