#!/bin/bash -

TRS='
	–	SQRT\s
	—	~=
	˜	<=
	™	>=
		^2
	¿	(c)
' TRS1='
	€	-
		|
	‚	+
	ƒ	+
	„	+
	…	+
	†	|
	‡	|
	ˆ	-
	‰	-
	Š	|
	‹	"
	Œ	_
		\#
	Ž	[
		]
		\#
	‘	\#
	’	\#
	“	/
	”	\#
	•	*
	–	V
	—	~
	˜	<
	™	>
	š	 
	›	/
	œ	o
		2
	ž	.
	Ÿ	:
	 	=
	¡	|
	¢	+
	£	ñ
	¤	+
	¥	+
	¦	+
	§	+
	¨	+
	©	+
	ª	+
	«	+
	¬	+
	­	+
	®	+
	¯	|
	°	|
	±	|
	²	|
	³	¡
	´	|
	µ	|
	¶	=
	·	-
	¸	=
	¹	=
	º	-
	»	=
	¼	|
	½	|
	¾	|
	¿	c
	À	î
	Á	Ð
	Â	Ñ
	Ã	æ
	Ä	Ô
	Å	Õ
	Æ	ä
	Ç	Ó
	È	å
	É	Ø
	Ê	Ù
	Ë	Ú
	Ì	Û
	Í	Ü
	Î	Ý
	Ï	Þ
	Ð	ß
	Ñ	ï
	Ò	à
	Ó	á
	Ô	â
	Õ	ã
	×	Ò
	Ø	ì
	Ù	ë
	Ú	×
	Û	è
	Ü	í
	Ý	é
	Þ	ç
	ß	ê
	à	Î
	á	°
	â	±
	ã	Æ
	ä	´
	å	µ
	æ	Ä
	ç	³
	è	Å
	é	¸
	ê	¹
	ë	º
	ì	»
	í	¼
	î	½
	ï	¾
	ð	¿
	ñ	Ï
	ò	À
	ó	Á
	ô	Â
	õ	Ã
	ö	¶
	÷	²
	ø	Ì
	ù	Ë
	ú	·
	û	È
	ü	Í
	ý	É
	þ	Ç
	ÿ	Ê
' MIME=iso-8859-5 "${0%/*}/../aux/charset-charset" koi8r-iso5
