#!/bin/bash -

TRS='
	–	SQRT\s
	—	~=
	˜	<=
	™	>=
		^2
' TRS1='
	€	-
		|
	‚	+
	ƒ	+
	„	+
	…	+
	†	|
	‡	|
	ˆ	-
	‰	-
	Š	|
	‹	"
	Œ	_
		\#
	Ž	[
		]
		\#
	‘	\#
	’	\#
	“	/
	”	\#
	–	V
	—	~
	˜	<
	™	>
	š	 
	›	/
	œ	°
		2
	ž	·
	Ÿ	:
	 	=
	¡	|
	¢	+
	£	¸
	¤	+
	¥	+
	¦	+
	§	+
	¨	+
	©	+
	ª	+
	«	+
	¬	+
	­	+
	®	+
	¯	|
	°	|
	±	|
	²	|
	³	¨
	´	|
	µ	|
	¶	=
	·	-
	¸	=
	¹	=
	º	-
	»	=
	¼	|
	½	|
	¾	|
	¿	©
	À	þ
	Á	à
	Â	á
	Ã	ö
	Ä	ä
	Å	å
	Æ	ô
	Ç	ã
	È	õ
	É	è
	Ê	é
	Ë	ê
	Ì	ë
	Í	ì
	Î	í
	Ï	î
	Ð	ï
	Ñ	ÿ
	Ò	ð
	Ó	ñ
	Ô	ò
	Õ	ó
	Ö	æ
	×	â
	Ø	ü
	Ù	û
	Ú	ç
	Û	ø
	Ü	ý
	Ý	ù
	Þ	÷
	ß	ú
	à	Þ
	á	À
	â	Á
	ã	Ö
	ä	Ä
	å	Å
	æ	Ô
	ç	Ã
	è	Õ
	é	È
	ê	É
	ë	Ê
	ì	Ë
	í	Ì
	î	Í
	ï	Î
	ð	Ï
	ñ	ß
	ò	Ð
	ó	Ñ
	ô	Ò
	õ	Ó
	ö	Æ
	÷	Â
	ø	Ü
	ù	Û
	ú	Ç
	û	Ø
	ü	Ý
	ý	Ù
	þ	×
	ÿ	Ú
' MIME=windows-1251 "${0%/*}/../aux/charset-charset" koi8r-cp1251
