#!/bin/bash -

TRS='
		^2
' TRS1='
	€	-
		|
	‚	+
	ƒ	+
	„	+
	…	+
	†	|
	‡	|
	ˆ	-
	‰	-
	Š	|
	‹	"
	Œ	_
		\#
	Ž	[
		]
		\#
	‘	\#
	’	\#
	“	/
	”	\#
	•	¥
	–	Ã
	—	Å
	˜	²
	™	³
	š	Ê
	›	/
	œ	¡
		2
	ž	¥
	Ÿ	Ö
	 	=
	¡	|
	¢	+
	£	Þ
	¤	+
	¥	+
	¦	+
	§	+
	¨	+
	©	+
	ª	+
	«	+
	¬	+
	­	+
	®	+
	¯	|
	°	|
	±	|
	²	|
	³	Ý
	´	|
	µ	|
	¶	=
	·	-
	¸	=
	¹	=
	º	-
	»	=
	¼	|
	½	|
	¾	|
	¿	©
	À	þ
	Á	à
	Â	á
	Ã	ö
	Ä	ä
	Å	å
	Æ	ô
	Ç	ã
	È	õ
	É	è
	Ê	é
	Ë	ê
	Ì	ë
	Í	ì
	Î	í
	Ï	î
	Ð	ï
	Ñ	ß
	Ò	ð
	Ó	ñ
	Ô	ò
	Õ	ó
	Ö	æ
	×	â
	Ø	ü
	Ù	û
	Ú	ç
	Û	ø
	Ü	ý
	Ý	ù
	Þ	÷
	ß	ú
	à	ž
	á	€
	â	
	ã	–
	ä	„
	å	…
	æ	”
	ç	ƒ
	è	•
	é	ˆ
	ê	‰
	ë	Š
	ì	‹
	í	Œ
	î	
	ï	Ž
	ð	
	ñ	Ÿ
	ò	
	ó	‘
	ô	’
	õ	“
	ö	†
	÷	‚
	ø	œ
	ù	›
	ú	‡
	û	˜
	ü	
	ý	™
	þ	—
	ÿ	š
' MIME=x-maccyr "${0%/*}/../aux/charset-charset" koi8r-maccyr
