#!/bin/bash -

TRS='
	—	~=
	˜	<=
	™	>=
		^2
	¿	(c)
' TRS1='
	€	Ä
		³
	‚	Ú
	ƒ	¿
	„	À
	…	Ù
	†	Ã
	‡	´
	ˆ	Â
	‰	Á
	Š	Å
	‹	ß
	Œ	Ü
		Û
	Ž	Ý
		Þ
		°
	‘	±
	’	²
	“	/
	”	þ
	•	ù
	–	û
	—	~
	˜	<
	™	>
	š	ÿ
	›	/
	œ	ø
		2
	ž	ú
	Ÿ	:
	 	Í
	¡	º
	¢	Õ
	£	ñ
	¤	Ö
	¥	É
	¦	¸
	§	·
	¨	»
	©	Ô
	ª	Ó
	«	È
	¬	¾
	­	½
	®	¼
	¯	Æ
	°	Ç
	±	Ì
	²	µ
	³	ð
	´	¶
	µ	¹
	¶	Ñ
	·	Ò
	¸	Ë
	¹	Ï
	º	Ð
	»	Ê
	¼	Ø
	½	×
	¾	Î
	¿	c
	À	î
	Á	 
	Â	¡
	Ã	æ
	Ä	¤
	Å	¥
	Æ	ä
	Ç	£
	È	å
	É	¨
	Ê	©
	Ë	ª
	Ì	«
	Í	¬
	Î	­
	Ï	®
	Ð	¯
	Ñ	ï
	Ò	à
	Ó	á
	Ô	â
	Õ	ã
	Ö	¦
	×	¢
	Ø	ì
	Ù	ë
	Ú	§
	Û	è
	Ü	í
	Ý	é
	Þ	ç
	ß	ê
	à	ž
	á	€
	â	
	ã	–
	ä	„
	å	…
	æ	”
	ç	ƒ
	è	•
	é	ˆ
	ê	‰
	ë	Š
	ì	‹
	í	Œ
	î	
	ï	Ž
	ð	
	ñ	Ÿ
	ò	
	ó	‘
	ô	’
	õ	“
	ö	†
	÷	‚
	ø	œ
	ù	›
	ú	‡
	û	˜
	ü	
	ý	™
	þ	—
	ÿ	š
' MIME=cp866 "${0%/*}/../aux/charset-charset" koi8r-cp866
