#!/bin/bash -

TRS='
	­	!=
	°	oo
	²	<=
	³	>=
	Ã	SQRT\s
	Å	~=
' TRS1='
	€	À
		Á
	‚	Â
	ƒ	Ã
	„	Ä
	…	Å
	†	Æ
	‡	Ç
	ˆ	È
	‰	É
	Š	Ê
	‹	Ë
	Œ	Ì
		Í
	Ž	Î
		Ï
		Ð
	‘	Ñ
	’	Ò
	“	Ó
	”	Ô
	•	Õ
	–	Ö
	—	×
	˜	Ø
	™	Ù
	š	Ú
	›	Û
	œ	Ü
		Ý
	ž	Þ
	Ÿ	ß
	 	†
	¡	°
	¢	¥
	£	L
	¤	§
	¥	•
	¦	¶
	§	²
	¨	®
	ª	™
	«	€
	¬	
	­	!
	®	
	¯	ƒ
	°	%
	²	<
	³	>
	´	³
	¶	´
	·	£
	¸	ª
	¹	º
	º	¯
	»	¿
	¼	Š
	½	š
	¾	Œ
	¿	œ
	À	¼
	Á	½
	Â	¬
	Ã	V
	Ä	f
	Å	~
	Æ	D
	Ç	«
	È	»
	É	…
	Ê	 
	Ë	Ž
	Ì	ž
	Í	
	Î	
	Ï	¾
	Ð	–
	Ñ	—
	Ò	“
	Ó	”
	Ô	‘
	Õ	’
	Ö	:
	×	„
	Ø	¡
	Ù	¢
	Ú	
	Û	Ÿ
	Ü	¹
	Ý	¨
	Þ	¸
	ß	ÿ
	ÿ	¤
' MIME=windows-1251 "${0%/*}/../aux/charset-charset" maccyr-cp1251
