#!/bin/bash -

TRS='
	¦	P:
	¨	(R)
	©	(c)
	ª	(TM)
	­	!=
	°	oo
	±	+-
	²	<=
	³	>=
	Ã	SQRT\s
	Å	~=
	Ç	<<
	È	>>
	É	...
	Ñ	--
	ÿ	CUR
' TRS1='
	€	°
		±
	‚	²
	ƒ	³
	„	´
	…	µ
	†	¶
	‡	·
	ˆ	¸
	‰	¹
	Š	º
	‹	»
	Œ	¼
		½
	Ž	¾
		¿
		À
	‘	Á
	’	Â
	“	Ã
	”	Ä
	•	Å
	–	Æ
	—	Ç
	˜	È
	™	É
	š	Ê
	›	Ë
	œ	Ì
		Í
	ž	Î
	Ÿ	Ï
	 	+
	¡	o
	¢	³
	£	L
	¤	ý
	¥	*
	¦	P
	§	¦
	¨	R
	©	c
	«	¢
	¬	ò
	­	!
	®	£
	¯	ó
	°	%
	²	<
	³	>
	´	ö
	µ	u
	¶	Ó
	·	¨
	¸	¤
	¹	ô
	º	§
	»	÷
	¼	©
	½	ù
	¾	ª
	¿	ú
	À	ø
	Á	¥
	Â	~
	Ã	V
	Ä	f
	Å	~
	Æ	D
	Ç	<
	È	>
	É	.
	Ê	 
	Ë	«
	Ì	û
	Í	¬
	Î	ü
	Ï	õ
	Ð	-
	Ñ	-
	Ò	"
	Ó	"
	Ô	`
	Õ	'\''
	Ö	:
	×	"
	Ø	®
	Ù	þ
	Ú	¯
	Û	ÿ
	Ü	ð
	Ý	¡
	Þ	ñ
	ß	ï
	à	Ð
	á	Ñ
	â	Ò
	ã	Ó
	ä	Ô
	å	Õ
	æ	Ö
	ç	×
	è	Ø
	é	Ù
	ê	Ú
	ë	Û
	ì	Ü
	í	Ý
	î	Þ
	ï	ß
	ð	à
	ñ	á
	ò	â
	ó	ã
	ô	ä
	õ	å
	ö	æ
	÷	ç
	ø	è
	ù	é
	ú	ê
	û	ë
	ü	ì
	ý	í
	þ	î
	ÿ	*
\[ª±\] ?
' MIME=iso-8859-5 "${0%/*}/../aux/charset-charset" maccyr-iso5
