#!/bin/bash -

VARIANT_de='
	€	AE
	…	OE
	†	UE
	Š	ae
	š	oe
	Ÿ	ue
' VARIANT_vi='
	ƒ	E'\''
	ˆ	a`
	‰	a^
	Ž	e'\''
		e`
		e^
	™	o^
		u`
' TRS='
		^1
	„	^3
	“	(TM)
	—	\s1/2
	˜	%%
	œ	\!
	§	ss
	¨	(R)
	©	(c)
	¬	S:
	­	!=
	Ç	<<
	È	>>
	É	...
	Ï	oe
	Ñ	--
' TRS1='
	€	A
		1
	‚	ý
	ƒ	E
	„	3
	…	O
	†	U
	‡	"
	ˆ	a
	‰	a
	Š	a
	‹	'\''
	Œ	"
		c
	Ž	e
		e
		e
	‘	e
	’	L
	”	i
	•	i
	–	ù
	—	/
	™	o
	š	o
	›	|
	œ	-
		u
	ž	u
	Ÿ	u
	 	Å
	¡	‚
	¢	ƒ
	£	‡
	¤	Š
	¥	
	¦	
	§	s
	¨	R
	©	c
	ª	‘
	«	ô
	¬	S
	­	Ø
	®	ø
	¯	ú
	°	€
	±	ñ
	²	ó
	³	ò
	´	Y
	µ	
	¶	„
	·	…
	¸	†
	¹	ˆ
	º	‰
	»	‹
	¼	”
	½	õ
	¾	–
	¿	—
	À	á
	Á	Œ
	Â	~
	Ã	Ž
	Ä	
	Å	÷
	Æ	’
	Ç	<
	È	>
	É	.
	Ê	ÿ
	Ë	“
	Ì	•
	Í	ê
	Î	ë
	Ï	o
	Ð	-
	Ñ	-
	Ò	"
	Ó	"
	Ô	`
	Õ	'\''
	Ö	ö
	×	ì
	Ø	í
	Ù	î
	Ú	ï
	Û	â
	Ü	ã
	Ý	å
	Þ	æ
	ß	ð
	à	ç
	á	˜
	â	™
	ã	¯
	ä	›
	å	œ
	æ	­
	ç	š
	è	ž
	é	 
	ê	¥
	ë	¡
	ì	¢
	í	£
	î	¤
	ï	¦
	ð	§
	ñ	é
	ò	¨
	ó	©
	ô	«
	õ	Ÿ
	ö	à
	÷	ª
	ø	®
	ù	¬
	ú	
	û	ä
	ü	è
	ý	i
	þ	u
\[“˜\] þ
' MIME=cp737 "${0%/*}/../aux/charset-charset" macgreek-cp737
