#!/bin/bash -

TRS='
	­	!=
	°	oo
	²	<=
	³	>=
	·	SUM\s
	¸	PROD\s
	º	INT\s
	½	OHM
	Ã	SQRT\s
	Å	~=
	×	<>
' TRS1='
	€	Ä
		Å
	‚	Ç
	ƒ	É
	„	Ñ
	…	Ö
	†	Ü
	‡	á
	ˆ	à
	‰	â
	Š	ä
	‹	ã
	Œ	å
		ç
	Ž	é
		è
		ê
	‘	ë
	’	í
	“	ì
	”	î
	•	ï
	–	ñ
	—	ó
	˜	ò
	™	ô
	š	ö
	›	õ
	œ	ú
		ù
	ž	û
	Ÿ	ü
	 	†
	¡	°
	¤	§
	¥	•
	¦	¶
	§	ß
	¨	®
	ª	™
	«	´
	¬	¨
	­	!
	®	Æ
	¯	Ø
	°	%
	²	<
	³	>
	´	¥
	¶	d
	·	S
	¸	P
	¹	p
	»	ª
	¼	º
	½	O
	¾	æ
	¿	ø
	À	¿
	Á	¡
	Â	¬
	Ã	V
	Ä	ƒ
	Å	~
	Æ	D
	Ç	«
	È	»
	É	…
	Ê	 
	Ë	À
	Ì	Ã
	Í	Õ
	Î	Œ
	Ï	œ
	Ð	–
	Ñ	—
	Ò	“
	Ó	”
	Ô	‘
	Õ	’
	Ö	÷
	Ø	ÿ
	Ù	Ÿ
	Ú	Ð
	Û	ð
	Ü	Ý
	Ý	ý
	ß	þ
	à	‡
	á	·
	â	‚
	ã	„
	ä	‰
	å	Â
	æ	Ê
	ç	Á
	è	Ë
	é	È
	ê	Í
	ë	Î
	ì	Ï
	í	Ì
	î	Ó
	ï	Ô
	ñ	Ò
	ò	Ú
	ó	Û
	ô	Ù
	ö	ˆ
	÷	˜
	ø	¯
	ù	~
	ú	.
	û	°
	ü	¸
	ý	"
	þ	,
	ÿ	^
\[º×ð\] ?
' MIME=windows-1254 "${0%/*}/../aux/charset-charset" mactur-cp1254
