#!/bin/bash -

VARIANT_bg='
	ะฉ	SHT
	ั	sht
' VARIANT_de='
	ร	AE
	ร–	OE
	ร	UE
	รค	ae
	รถ	oe
' VARIANT_hr='
	ฤ	DJ
	ฤ‘	dj
' VARIANT_vi='
	ร€	A`
	ร	A'\''
	ร	A^
	ร	A~
	ร	E`
	ร	E'\''
	ร	E^
	ร	I`
	ร	I'\''
	ร’	O`
	ร“	O'\''
	ร”	O^
	ร•	O~
	ร	U`
	ร	U'\''
	ร	Y'\''
	รก	a'\''
	รฃ	a~
	รฌ	i`
	รญ	i'\''
	รฒ	o`
	รณ	o'\''
	รต	o~
	รบ	u'\''
	รฝ	y'\''
	ฤ	A(
	ฤ	a(
	ฤ	DD
	ฤ‘	dd
	ฤจ	I~
	ฤฉ	i~
	ลจ	U~
	ลฉ	u~
' VARIANT1_bg='
	ะช	Y
	ั	y
' VARIANT1_ua='
	ะ	Y
	ะธ	y
' APPROX='
	ล	’n
	โ	ฐC
	โ	ฐF
	โ	ณ\\/
	โ	(ท)
' APPROX1='
	ว–	ü
	ว	ü
	ว	ü
	ว	ü
	ห	ฐ
	ฮ	ท
	ั	่
	ั	๛
	ั	โ
	ั‘	๋
	ั—	๏
	แธฏ	๏
	แบฅ	โ
	แบง	โ
	แบฉ	โ
	แบซ	โ
	แบญ	โ
	แบฟ	๊
	แป	๊
	แป	๊
	แป…	๊
	แป	๊
	แป‘	๔
	แป“	๔
	แป•	๔
	แป—	๔
	แป	๔
	โ€’	–
	โ€•	—
	โ€	‘
	โ€ง	ท
	โค	ฃ
	โ	ฐ
	โ	•
	โ	ท
	โ…	ท
	โฎ	…
	โฏ	…
	โฐ	…
	โฑ	…
	โ	ฌ
	โ“	ื
' REPLACE='?' MIME=windows-1256 "${0%/*}/../aux/UTF8-charset" -rf "${0%/*}/../aux/charsets/cp1256"
